import * as React from "react";
export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: "default" | "secondary" | "outline" | "ghost" | "destructive" | "link";
  size?: "default" | "xs" | "sm" | "lg" | "icon" | "icon-sm" | "icon-lg";
  href?: string;
};
export type BadgeProps = React.HTMLAttributes<HTMLSpanElement> & { variant?: "default" | "secondary" | "outline" | "destructive" };
export type InputProps = React.InputHTMLAttributes<HTMLInputElement>;
export type TextareaProps = React.TextareaHTMLAttributes<HTMLTextAreaElement>;
export type LabelProps = React.LabelHTMLAttributes<HTMLLabelElement>;
export type CardProps = React.HTMLAttributes<HTMLDivElement>;
export type AlertProps = React.HTMLAttributes<HTMLDivElement> & { variant?: "default" | "destructive" };
export type CheckboxProps = Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onChange"> & {
  checked?: boolean; defaultChecked?: boolean; onCheckedChange?: (checked: boolean) => void;
};
export type SwitchProps = CheckboxProps;
export type TabsProps = React.HTMLAttributes<HTMLDivElement> & { value?: string; defaultValue?: string; onValueChange?: (value: string) => void };
export type TabsTriggerProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { value: string };
export type TabsContentProps = React.HTMLAttributes<HTMLDivElement> & { value: string };
export type AvatarProps = React.HTMLAttributes<HTMLSpanElement>;
export type SeparatorProps = React.HTMLAttributes<HTMLDivElement> & { orientation?: "horizontal" | "vertical"; decorative?: boolean };
export type SkeletonProps = React.HTMLAttributes<HTMLDivElement>;
export type ProgressProps = React.HTMLAttributes<HTMLDivElement> & { value?: number };
export type KbdProps = React.HTMLAttributes<HTMLElement>;

export declare function Button(props: ButtonProps): JSX.Element;
export declare function Badge(props: BadgeProps): JSX.Element;
export declare function Input(props: InputProps): JSX.Element;
export declare function Textarea(props: TextareaProps): JSX.Element;
export declare function Label(props: LabelProps): JSX.Element;
export declare function Card(props: CardProps): JSX.Element;
export declare function CardHeader(props: CardProps): JSX.Element;
export declare function CardTitle(props: CardProps): JSX.Element;
export declare function CardDescription(props: CardProps): JSX.Element;
export declare function CardContent(props: CardProps): JSX.Element;
export declare function CardFooter(props: CardProps): JSX.Element;
export declare function Alert(props: AlertProps): JSX.Element;
export declare function AlertTitle(props: CardProps): JSX.Element;
export declare function AlertDescription(props: CardProps): JSX.Element;
export declare function Checkbox(props: CheckboxProps): JSX.Element;
export declare function Switch(props: SwitchProps): JSX.Element;
export declare function Tabs(props: TabsProps): JSX.Element;
export declare function TabsList(props: CardProps): JSX.Element;
export declare function TabsTrigger(props: TabsTriggerProps): JSX.Element;
export declare function TabsContent(props: TabsContentProps): JSX.Element;
export declare function Avatar(props: AvatarProps): JSX.Element;
export declare function AvatarImage(props: React.ImgHTMLAttributes<HTMLImageElement>): JSX.Element | null;
export declare function AvatarFallback(props: AvatarProps): JSX.Element;
export declare function Separator(props: SeparatorProps): JSX.Element;
export declare function Skeleton(props: SkeletonProps): JSX.Element;
export declare function Progress(props: ProgressProps): JSX.Element;
export declare function Kbd(props: KbdProps): JSX.Element;
export declare function cn(...classes: Array<string | false | null | undefined>): string;
